### ISSUE TITLE
openapi: Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-express#6]
Understand that this is still under development. I am reporting this for tracking -

Running the yang-express/example petstore, I get the following error -

```
bash-4.3$ curl localhost:5000/openapi.spec
{
  "error": {
    "message": "Cannot read property 'nodes' of undefined"
  }
}bash-4.3$
```

Server Log -

```
TypeError: Cannot read property 'nodes' of undefined
  at Function.restjson.paths (.../yang-express/lib/restjson.js:138:18)
  at .../yang-express/lib/openapi.js:57:27
```

I am using following versions of dependencies : 
    "yang-express": "^0.3.9",
    "yang-js": "^0.15.16",

The latest changes to yang-js project may have broken it.

**Comment by ramukima** [comment]
Review pull request - https://github.com/corenova/yang-express/pull/7 (may be a wrong way to fix it but the fix works).

**Comment by ramukima** [comment]
merged, closing
